version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    volumes:
        - db_data:/var/lib/influxdb
    hostname: influxdb
    networks:
      - dbconnect
      - front
    environment:
      INFLUX_ROOT_PASSWORD_FILE: /run/secrets/influx-db-password-secret
      INFLUX_DATABASE: TransfermarkT
    deploy:
      placement:
        constraints:
          - node.labels.influxdb == true
    ports:
      - "8086:8086"
    secrets:
      - influx-db-password-secret
      
  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    hostname: grafana
    networks:
      - front
    environment:
      GRAFANA_DB_HOST: influxdb:8086
      GRAFANA_USERNAME: alexmarin
      GRAFANA_PASSWORD: proiectcc
      GRAFANA_DB_NAME: grafana_db
      GF_SECURITY_ADMIN_PASSWORD: proiectcc
    ports:
      - "3000:3000"
    volumes:
      - grf_data:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.labels.grafana == true
          
  server:
    image: alexmarin88/proiect-cc:server
    hostname: server
    networks:
      - backend
      - dbconnect
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first
    depends_on:
      - influxdb
                  
  admin:
    image: alexmarin88/proiect-cc:admin
    hostname: admin
    networks:
      - dbconnect
      - apigw
    depends_on:
      - influxdb
      - server
    
  client:
    image: ioanamoraru14/proiect-cc:client
    hostname: client
    networks:
      - backend
      - apigw
    depends_on:
      - server

  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml 
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
    deploy:
      placement:
        constraints: [node.role == manager] 
    networks:
      - apigw

  auth:
    image: ioanamoraru14/proiect-cc:auth
    networks:
      - apigw
      - database-admin
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        order: start-first
      rollback_config:
        order: stop-first
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-db-password-secret
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
      - proiect-db:/var/lib/mysql
    networks:
      - database-admin
      - backend
    secrets:
      - mysql-db-password-secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 7000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - database-admin

networks:
  front:
    driver: overlay
  backend:
    driver: overlay
    attachable: true
  dbconnect:
    driver: overlay
    attachable: true
  database-admin:
  apigw:

volumes:
    db_data: {}
    grf_data: {}
    proiect-db:

secrets:
  influx-db-password-secret:
    external: true
  mysql-db-password-secret:
    external: true

